### ISSUE TITLE
Export in different formats

### ISSUE THREAD

**Issue by steinm** [sysPass/syspass-decrypter#6]
I may be blind, but I can't find an option to output the decrypted data in any other format than a table like format. Outputing json would be great.

**Comment by stloc** [comment]
https://github.com/stloc/syspass-decrypter/tree/export-json-csv I added --export option


https://github.com/sysPass/syspass-decrypter/pull/7

**Comment by nuxsmin** [comment]
Hello,

Although this could be used as an export tool, unfortunately it isn't the purpose of it, because it's a security tool, so I wouldn't recommend/implement an exporting option, because these generates files would provide an easy way to generate a data breach, so I'd rather prefer to let the data encrypted and decrypt it only when needed.

@stloc thank you for the useful PR, but as said above, data security tools should keep the data chain secured, so exporting it in plain formats will break the chain.

Regards
